import { jwccstrip, jwccminify } from "../src/index.mjs";
import { expect, test } from 'vitest'

test('jwccstrip json', () => {
  expect(jwccstrip('{}')).toBe('{}');
  expect(jwccstrip('[]')).toBe('[]');
  expect(jwccstrip('true')).toBe('true');
  expect(jwccstrip('false')).toBe('false');
  expect(jwccstrip('null')).toBe('null');
  expect(jwccstrip('123')).toBe('123');
  expect(jwccstrip('123.4')).toBe('123.4');
  expect(jwccstrip('123.4e-5')).toBe('123.4e-5');
  expect(jwccstrip('-123.45e+6')).toBe('-123.45e+6');
  expect(jwccstrip(' \t\r\n{ \t\r\n } \t\r\n')).toBe(' \t\r\n{ \t\r\n } \t\r\n');
  expect(jwccstrip(' \t\r\n[ \t\r\n ] \t\r\n')).toBe(' \t\r\n[ \t\r\n ] \t\r\n');
  expect(jwccstrip(' \t\r\ntrue \t\r\n')).toBe(' \t\r\ntrue \t\r\n');
  expect(jwccstrip(' \t\r\nfalse \t\r\n')).toBe(' \t\r\nfalse \t\r\n');
  expect(jwccstrip(' \t\r\nnull \t\r\n')).toBe(' \t\r\nnull \t\r\n');
  expect(jwccstrip(' \t\r\n123 \t\r\n')).toBe(' \t\r\n123 \t\r\n');
  expect(jwccstrip(' \t\r\n123.4 \t\r\n')).toBe(' \t\r\n123.4 \t\r\n');
  expect(jwccstrip(' \t\r\n123.4e-5 \t\r\n')).toBe(' \t\r\n123.4e-5 \t\r\n');
  expect(jwccstrip(' \t\r\n-123.45e+6 \t\r\n')).toBe(' \t\r\n-123.45e+6 \t\r\n');
  expect(jwccstrip('"string with spaces   , carriage return \\r \\r\\r tab \\t \\t\\t new line \\n \\n\\n and mix \\r\\n\\t\\r\\t\\n  commas, ,,  escaped quotes \\" \\"\\", escaped backslash \\\\ \\\\\\\\ "')).toBe('"string with spaces   , carriage return \\r \\r\\r tab \\t \\t\\t new line \\n \\n\\n and mix \\r\\n\\t\\r\\t\\n  commas, ,,  escaped quotes \\" \\"\\", escaped backslash \\\\ \\\\\\\\ "');
  expect(jwccstrip('[true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"]')).toBe('[true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"]');
  expect(jwccstrip('[\ntrue,\nfalse,\nnull,\n123,\n123.4e-5,\n-123.45e+6,\n"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n]')).toBe('[\ntrue,\nfalse,\nnull,\n123,\n123.4e-5,\n-123.45e+6,\n"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n]');
  expect(jwccstrip(' \t\r\n{ "a": true, "b": false, "c": null, "d": 123, "e": 123.4e-5, "f": -123.45e+6, "g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", "array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n')).toBe(' \t\r\n{ "a": true, "b": false, "c": null, "d": 123, "e": 123.4e-5, "f": -123.45e+6, "g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", "array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n');
  expect(jwccstrip(' \t\r\n{\n"a": true,\n"b": false,\n"c": null,\n"d": 123,\n"e": 123.4e-5,\n"f": -123.45e+6,\n"g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n"array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n')).toBe(' \t\r\n{\n"a": true,\n"b": false,\n"c": null,\n"d": 123,\n"e": 123.4e-5,\n"f": -123.45e+6,\n"g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n"array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n');
});
test('jwccstrip json with commas', () => {
  expect(jwccstrip('[123,]')).toBe('[123 ]');
  expect(jwccstrip('[123.4,]')).toBe('[123.4 ]');
  expect(jwccstrip('[123.4e-5,]')).toBe('[123.4e-5 ]');
  expect(jwccstrip('[-123.45e+6,]')).toBe('[-123.45e+6 ]');
  expect(jwccstrip('[123\n,]')).toBe('[123\n ]');
  expect(jwccstrip('[123.4\n,]')).toBe('[123.4\n ]');
  expect(jwccstrip('[123.4e-5\n,]')).toBe('[123.4e-5\n ]');
  expect(jwccstrip('[-123.45e+6\n,]')).toBe('[-123.45e+6\n ]');
  expect(jwccstrip('[\n123,\n]')).toBe('[\n123 \n]');
  expect(jwccstrip('[\n123.4,\n]')).toBe('[\n123.4 \n]');
  expect(jwccstrip('[\n123.4e-5,\n]')).toBe('[\n123.4e-5 \n]');
  expect(jwccstrip('[\n-123.45e+6,\n]')).toBe('[\n-123.45e+6 \n]');
  expect(jwccstrip('{"key":123,}')).toBe('{"key":123 }');
  expect(jwccstrip('{"key":123.4,}')).toBe('{"key":123.4 }');
  expect(jwccstrip('{"key":123.4e-5,}')).toBe('{"key":123.4e-5 }');
  expect(jwccstrip('{"key":-123.45e+6,}')).toBe('{"key":-123.45e+6 }');
  expect(jwccstrip('{"key":123\n,}')).toBe('{"key":123\n }');
  expect(jwccstrip('{"key":123.4\n,}')).toBe('{"key":123.4\n }');
  expect(jwccstrip('{"key":123.4e-5\n,}')).toBe('{"key":123.4e-5\n }');
  expect(jwccstrip('{"key":-123.45e+6\n,}')).toBe('{"key":-123.45e+6\n }');
  expect(jwccstrip('{"key":\n123,\n}')).toBe('{"key":\n123 \n}');
  expect(jwccstrip('{"key":\n123.4,\n}')).toBe('{"key":\n123.4 \n}');
  expect(jwccstrip('{"key":\n123.4e-5,\n}')).toBe('{"key":\n123.4e-5 \n}');
  expect(jwccstrip('{"key":\n-123.45e+6,\n}')).toBe('{"key":\n-123.45e+6 \n}');
  expect(jwccstrip('[true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //",]')).toBe('[true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //" ]');
  expect(jwccstrip('[\ntrue,\nfalse,\nnull,\n123,\n123.4e-5,\n-123.45e+6,\n"string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n]')).toBe('[\ntrue,\nfalse,\nnull,\n123,\n123.4e-5,\n-123.45e+6,\n"string // /* \\t\\r\\t\\n\\"\\\\*/ //" \n]');
  expect(jwccstrip('[true\n,false\n,null\n,123\n,123.4e-5\n,-123.45e+6\n,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n,]')).toBe('[true\n,false\n,null\n,123\n,123.4e-5\n,-123.45e+6\n,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n ]');
  expect(jwccstrip('[true\n,false\n,null\n,123\n,123.4e-5\n,-123.45e+6\n,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n,\n]')).toBe('[true\n,false\n,null\n,123\n,123.4e-5\n,-123.45e+6\n,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n \n]');
  expect(jwccstrip('{ "a": 1, "b": true, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", }')).toBe('{ "a": 1, "b": true, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"  }');
  expect(jwccstrip('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n}')).toBe('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //" \n}');
  expect(jwccstrip('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n,}')).toBe('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n }');
  expect(jwccstrip('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n,\n}')).toBe('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n \n}');
  expect(jwccstrip(' \t\r\n{ "a": true, "b": false, "c": null, "d": 123, "e": 123.4e-5, "f": -123.45e+6, "g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", "array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //", ], \t\r\n} \t\r\n')).toBe(' \t\r\n{ "a": true, "b": false, "c": null, "d": 123, "e": 123.4e-5, "f": -123.45e+6, "g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", "array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"  ]  \t\r\n} \t\r\n');
  expect(jwccstrip(' \t\r\n{\n"a": true,\n"b": false,\n"c": null,\n"d": 123,\n"e": 123.4e-5,\n"f": -123.45e+6,\n"g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n"array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n')).toBe(' \t\r\n{\n"a": true,\n"b": false,\n"c": null,\n"d": 123,\n"e": 123.4e-5,\n"f": -123.45e+6,\n"g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n"array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n');
});
test('jwccstrip json with commas and comments', () => {
  expect(jwccstrip('{ "a": 1, //123\t123\r\n"b": true}')).toBe('{ "a": 1,      \t   \r\n"b": true}');
  expect(jwccstrip('{ "a": 1, /* comment */ "b": true /* comment */, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"  /*comment\ncomment*/  }')).toBe('{ "a": 1,               "b": true              , "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"           \n           }');
  expect(jwccstrip('{ "a": 1, /* comment */ "b": true /* comment */, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", /*comment\ncomment*/  }')).toBe('{ "a": 1,               "b": true              , "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"           \n           }');
  expect(jwccstrip('{ "a": 1, /* comment */ "b": true /* comment */, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"  /*comment\ncomment*/, }')).toBe('{ "a": 1,               "b": true              , "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"           \n           }');
  expect(jwccstrip('{ "a": 1, // comment \n  "b": true// comment\n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //" // comment\n }')).toBe('{ "a": 1,            \n  "b": true          \n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"           \n }');
  expect(jwccstrip('{ "a": 1, // comment \n  "b": true// comment\n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",// comment\n }')).toBe('{ "a": 1,            \n  "b": true          \n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"           \n }');
  expect(jwccstrip('{ "a": 1, // comment \n  "b": true// comment\n//comment\n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",// comment\n//comment\n }')).toBe('{ "a": 1,            \n  "b": true          \n         \n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"           \n         \n }');
  expect(jwccstrip('{ "a": 1, /* comment // not single-line comment\n // not single-line comment */ "b": true // comment /* not multiline comment\n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //" // comment\n /*comment\ncomment*/ // comment\n//comment\n  , /*comment\ncomment*/ // comment\n//comment\n }')).toBe('{ "a": 1,                                      \n                               "b": true                                    \n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"           \n          \n                    \n         \n             \n                    \n         \n }');
});
test('jwccstrip bad json', () => {
  expect(jwccstrip('{   ')).toBe('{   ');
  expect(jwccstrip(' }   ')).toBe(' }   ');
  expect(jwccstrip('   [   ')).toBe('   [   ');
  expect(jwccstrip(' ]   ')).toBe(' ]   ');
  expect(jwccstrip(',]   ')).toBe(' ]   ');
  expect(jwccstrip(' ,   ')).toBe(' ,   ');
  expect(jwccstrip(' , ,  , ')).toBe(' , ,  , ');
  expect(jwccstrip('a b  c\nd\r\ne')).toBe('a b  c\nd\r\ne');
  expect(jwccstrip('{"a": 1,')).toBe('{"a": 1,');
  expect(jwccstrip('"a": 1, }')).toBe('"a": 1  }');
  expect(jwccstrip('"a": 1, , }')).toBe('"a": 1    }');
  expect(jwccstrip('[123')).toBe('[123');
  expect(jwccstrip('[123,')).toBe('[123,');
  expect(jwccstrip('123]')).toBe('123]');
  expect(jwccstrip('123 , ]')).toBe('123   ]');
  expect(jwccstrip('123 ,  , ]')).toBe('123      ]');
  expect(jwccstrip('[123 true false "not remove  string   spaces"')).toBe('[123 true false "not remove  string   spaces"');
  expect(jwccstrip('{} /')).toBe('{} /');
  expect(jwccstrip('{} /* comment')).toBe('{}           ');
  expect(jwccstrip('{} */')).toBe('{} */');
  expect(jwccstrip('{} /\n/')).toBe('{} /\n/');
  expect(jwccstrip('{ // ，}')).toBe('{      ');
});

test('jwccminify json', () => {
  expect(jwccminify('{}')).toBe('{}');
  expect(jwccminify('[]')).toBe('[]');
  expect(jwccminify('true')).toBe('true');
  expect(jwccminify('false')).toBe('false');
  expect(jwccminify('null')).toBe('null');
  expect(jwccminify('123')).toBe('123');
  expect(jwccminify('123.4')).toBe('123.4');
  expect(jwccminify('123.4e-5')).toBe('123.4e-5');
  expect(jwccminify('-123.45e+6')).toBe('-123.45e+6');
  expect(jwccminify('"string with spaces   , carriage return \\r \\r\\r tab \\t \\t\\t new line \\n \\n\\n and mix \\r\\n\\t\\r\\t\\n  commas, ,,  escaped quotes \\" \\"\\", escaped backslash \\\\ \\\\\\\\ "')).toBe('"string with spaces   , carriage return \\r \\r\\r tab \\t \\t\\t new line \\n \\n\\n and mix \\r\\n\\t\\r\\t\\n  commas, ,,  escaped quotes \\" \\"\\", escaped backslash \\\\ \\\\\\\\ "');
  expect(jwccminify('[true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"]')).toBe('[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]');
  expect(jwccminify('[\ntrue,\nfalse,\nnull,\n123,\n123.4e-5,\n-123.45e+6,\n"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n]')).toBe('[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]');
  expect(jwccminify(' \t\r\n{ "a": true, "b": false, "c": null, "d": 123, "e": 123.4e-5, "f": -123.45e+6, "g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", "array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n')).toBe('{"a":true,"b":false,"c":null,"d":123,"e":123.4e-5,"f":-123.45e+6,"g":"string // /* \\t\\r\\t\\n\\"\\\\*/ //","array":[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]}');
  expect(jwccminify(' \t\r\n{\n"a": true,\n"b": false,\n"c": null,\n"d": 123,\n"e": 123.4e-5,\n"f": -123.45e+6,\n"g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n"array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n')).toBe('{"a":true,"b":false,"c":null,"d":123,"e":123.4e-5,"f":-123.45e+6,"g":"string // /* \\t\\r\\t\\n\\"\\\\*/ //","array":[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]}');
});
test('jwccminify json with commas', () => {
  expect(jwccminify('[123,]')).toBe('[123]');
  expect(jwccminify('[123.4,]')).toBe('[123.4]');
  expect(jwccminify('[123.4e-5,]')).toBe('[123.4e-5]');
  expect(jwccminify('[-123.45e+6,]')).toBe('[-123.45e+6]');
  expect(jwccminify('[123\n,]')).toBe('[123]');
  expect(jwccminify('[123.4\n,]')).toBe('[123.4]');
  expect(jwccminify('[123.4e-5\n,]')).toBe('[123.4e-5]');
  expect(jwccminify('[-123.45e+6\n,]')).toBe('[-123.45e+6]');
  expect(jwccminify('[\n123,\n]')).toBe('[123]');
  expect(jwccminify('[\n123.4,\n]')).toBe('[123.4]');
  expect(jwccminify('[\n123.4e-5,\n]')).toBe('[123.4e-5]');
  expect(jwccminify('[\n-123.45e+6,\n]')).toBe('[-123.45e+6]');
  expect(jwccminify('{"key":123,}')).toBe('{"key":123}');
  expect(jwccminify('{"key":123.4,}')).toBe('{"key":123.4}');
  expect(jwccminify('{"key":123.4e-5,}')).toBe('{"key":123.4e-5}');
  expect(jwccminify('{"key":-123.45e+6,}')).toBe('{"key":-123.45e+6}');
  expect(jwccminify('{"key":123\n,}')).toBe('{"key":123}');
  expect(jwccminify('{"key":123.4\n,}')).toBe('{"key":123.4}');
  expect(jwccminify('{"key":123.4e-5\n,}')).toBe('{"key":123.4e-5}');
  expect(jwccminify('{"key":-123.45e+6\n,}')).toBe('{"key":-123.45e+6}');
  expect(jwccminify('{"key":\n123,\n}')).toBe('{"key":123}');
  expect(jwccminify('{"key":\n123.4,\n}')).toBe('{"key":123.4}');
  expect(jwccminify('{"key":\n123.4e-5,\n}')).toBe('{"key":123.4e-5}');
  expect(jwccminify('{"key":\n-123.45e+6,\n}')).toBe('{"key":-123.45e+6}');
  expect(jwccminify('[true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //",]')).toBe('[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]');
  expect(jwccminify('[\ntrue,\nfalse,\nnull,\n123,\n123.4e-5,\n-123.45e+6,\n"string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n]')).toBe('[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]');
  expect(jwccminify('[true\n,false\n,null\n,123\n,123.4e-5\n,-123.45e+6\n,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n,]')).toBe('[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]');
  expect(jwccminify('[true\n,false\n,null\n,123\n,123.4e-5\n,-123.45e+6\n,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n,\n]')).toBe('[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]');
  expect(jwccminify('{ "a": 1, "b": true, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", }')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n}')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n,}')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{\n"a": 1,\n"b": true,\n"c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"\n,\n}')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify(' \t\r\n{ "a": true, "b": false, "c": null, "d": 123, "e": 123.4e-5, "f": -123.45e+6, "g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", "array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //", ], \t\r\n} \t\r\n')).toBe('{"a":true,"b":false,"c":null,"d":123,"e":123.4e-5,"f":-123.45e+6,"g":"string // /* \\t\\r\\t\\n\\"\\\\*/ //","array":[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]}');
  expect(jwccminify(' \t\r\n{\n"a": true,\n"b": false,\n"c": null,\n"d": 123,\n"e": 123.4e-5,\n"f": -123.45e+6,\n"g": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",\n"array": [true, false, null, 123, 123.4e-5, -123.45e+6, "string // /* \\t\\r\\t\\n\\"\\\\*/ //"] \t\r\n} \t\r\n')).toBe('{"a":true,"b":false,"c":null,"d":123,"e":123.4e-5,"f":-123.45e+6,"g":"string // /* \\t\\r\\t\\n\\"\\\\*/ //","array":[true,false,null,123,123.4e-5,-123.45e+6,"string // /* \\t\\r\\t\\n\\"\\\\*/ //"]}');
});
test('jwccminify json with commas and comments', () => {
  expect(jwccminify('{ "a": 1, /* comment */ "b": true /* comment */, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"  /*comment\ncomment*/  }')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{ "a": 1, /* comment */ "b": true /* comment */, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //", /*comment\ncomment*/  }')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{ "a": 1, /* comment */ "b": true /* comment */, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //"  /*comment\ncomment*/, }')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{ "a": 1, // comment \n  "b": true// comment\n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //" // comment\n }')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{ "a": 1, // comment \n  "b": true// comment\n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",// comment\n }')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{ "a": 1, // comment \n  "b": true// comment\n//comment\n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //",// comment\n//comment\n }')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
  expect(jwccminify('{ "a": 1, /* comment // not single-line comment\n // not single-line comment */ "b": true // comment /* not multiline comment\n, "c": "string // /* \\t\\r\\t\\n\\"\\\\*/ //" // comment\n /*comment\ncomment*/ // comment\n//comment\n  , /*comment\ncomment*/ // comment\n//comment\n }')).toBe('{"a":1,"b":true,"c":"string // /* \\t\\r\\t\\n\\"\\\\*/ //"}');
});
test('jwccminify bad json', () => {
  expect(jwccminify('{   ')).toBe('{');
  expect(jwccminify(' }   ')).toBe('}');
  expect(jwccminify('   [   ')).toBe('[');
  expect(jwccminify(' ]   ')).toBe(']');
  expect(jwccminify(' ,   ')).toBe(',');
  expect(jwccminify(' , ,  , ')).toBe(',,,');
  expect(jwccminify('a b  c\nd\r\ne')).toBe('abcde');
  expect(jwccminify('{"a": 1,')).toBe('{"a":1,');
  expect(jwccminify('"a": 1, }')).toBe('"a":1}');
  expect(jwccminify('"a": 1, , }')).toBe('"a":1}');
  expect(jwccminify('[123')).toBe('[123');
  expect(jwccminify('[123,')).toBe('[123,');
  expect(jwccminify('123]')).toBe('123]');
  expect(jwccminify('123 , ]')).toBe('123]');
  expect(jwccminify('123 ,  , ]')).toBe('123]');
  expect(jwccminify('[123 true false "not remove  string   spaces"')).toBe('[123truefalse"not remove  string   spaces"');
});
